name = "NumericalRecipes"
uuid = "bad5a67b-0cee-4d24-8535-48c98e857614"
authors = ["woclass <git@wo-class.cn> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
